Add docker-compose.yml
IgorIamshchikov/TaskManager pull request #1
Opened 2022-10-10 09:35 UTC by IgorIamshchikov

2022-10-10 15:18 UTC, greybutton requested changes
В TaskManager нужно использовать git-flow. Cоздать ветку develop, и от нее создавать ветки с кодом и в нее же сливать. develop — основная ветка разработки. Подробнее описано тут: https://learn.dualboot.ru/courses/5/lessons/73/practices/1064

2022-10-11 07:40 UTC, IgorIamshchikov commented
Создал и запушил ветки: main и develop. Делал их на основе ветки tmp. После изменил в PR в какую ветку мержим(tmp на develop). Все верно сделал?

2022-10-11 09:47 UTC, greybutton commented
ну как бы да, но откуда взялась ветка tmp? Странная штука какая то, ее по идее вообще не должно быть. И то что ветки main и develop делались на основе ветки tmp, ну ладно, но так обычно не делается

2022-10-11 09:48 UTC, greybutton approved these changes

2022-10-11 11:00 UTC, IgorIamshchikov commented
Было неправильное понимание. В предыдущем задании думал, что проект надо будет мержить в develop после апрува. По этому создал ветку tmp. Разобравшись понял, что следовало проект сразу делать в develop, а последующие задачи мержить из feature's. По крайней мере на данный момент такое понимание. Спасибо за разъяснения!

2022-10-11 11:15 UTC, merged