Feature/tasks
IgorIamshchikov/TaskManager pull request #15
Opened 2022-11-07 17:09 UTC by IgorIamshchikov

2022-11-07 23:53 UTC, IgorIamshchikov commented on app/javascript/components/TaskBoard/TaskBoard.js
> +import EditPopup from '../EditPopup/EditPopup';
Как лучше записывать import,  как записан здесь или "from components/EditPopup"?

2022-11-07 23:55 UTC, IgorIamshchikov commented on app/javascript/components/ColumnHeader/ColumnHeader.js
> +};
Имеет ли смысл так подробно расписывать пропы или хватило бы 'column' и 'onLoadMore'?

2022-11-08 08:17 UTC, greybutton requested changes
> Вопрос по компоненту Form. В здании было указано, что его необходимо создать компонент 'Form' внутри 'EditPopup'. Но не лучше ли создать его в директории с другими компонентами?
components/Form вместо components/EditPopup/components/Form

можно и в components/Form, но пока форма только в EditPopup используется, то можно ее держать там же, если появится переиспользование, то можно вынести на уровень повыше

2022-11-08 08:17 UTC, greybutton commented on app/javascript/components/ColumnHeader/ColumnHeader.js
> +};
В целом, хватило бы 'column' и 'onLoadMore', но подробно расписывать имеет смысл, чтобы сразу видеть структуры данных

2022-11-08 08:17 UTC, greybutton commented on app/javascript/components/EditPopup/EditPopup.js
> +import Form from './components/Form/Form';
`from './components/Form';`

2022-11-08 08:17 UTC, greybutton commented on app/javascript/components/TaskBoard/TaskBoard.js
> +import EditPopup from '../EditPopup/EditPopup';
from components/EditPopup

2022-11-08 08:17 UTC, greybutton commented on app/javascript/components/TaskBoard/TaskBoard.js
> +      ;{mode === MODES.ADD && <AddPopup onCreateCard={handleTaskCreate} onClose={handleClose} />}
`;` лишнее

2022-11-08 18:45 UTC, greybutton approved these changes

2022-11-08 20:13 UTC, merged